language: php
php:
  - 5.4
  - 5.5
notifications:
  irc:
    use_notice: true
    skip_join: true
    channels: ["irc.freenode.org#imbo"]
branches:
  only:
    - develop
    - master
before_script:
  - composer self-update
  - composer --dev install --prefer-source
script: phpunit -c tests
